name: Add to Sprint Board

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue or PR to project board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/alfaz-studio/projects/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
